version: '3.8'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.dev
  pgadmin:
    image: dpage/pgadmin4:4.6
    restart: always
    environment:
      - ./.env.dev
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    depends_on:
     - db

volumes:
  postgres_data:
