version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 Api:app
    volumes:
      - ./services/nginx/static:/home/app/web/project/static
      - ./services/nginx/media:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - rwm_internal
  
  db:
    image: mysql:5
    #restart: unless-stopped
    hostname: mysql
    environment:
      - ./.env.prod.db
    volumes:
      - ./services/database:/var/lib/mysql/
    networks:
      - rwm_internal
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./services/nginx
    volumes:
      - ./services/nginx/static:/home/app/web/project/static
      - ./services/nginx/media:/home/app/web/project/media
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
        - rwm_internal
  
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    #restart: unless-stopped
    environment:
      PMA_HOST: mysql
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./services/phpmyadmin:/var/lib/phpmyadmin
    networks:
      - rwm_internal


networks:
  rwm_internal:
    driver: bridge